### ISSUE TITLE
downloading all videos

### ISSUE THREAD

**Issue by essankov** [ankitjain28may/pythonResources#1]
Hi, what if I want to download all videos in the website? how the script will be?

**Comment by ankitjain28may** [comment]
Thanks, You can only download particular video by entering its download link.. You can't download all the videos from the website. I will later work on your suggested query.

**Comment by ankitjain28may** [comment]
hi @essankov I recently added a script that will download all the videos from the Youtube playlist.. if you wanna do that, you can now download through it.
