### ISSUE TITLE
not working on youtube

### ISSUE THREAD

**Issue by Nimit-Khurana** [ankitjain28may/pythonResources#2]
i tried both on the interpreter and run.py file, it gives the html of the page.
the link i used was https://youtu.be/Xh0-x1RFEOY

**Comment by ankitjain28may** [comment]
Try to download using this [file](https://github.com/ankitjain28may/pythonResources/tree/master/Download%20Youtube%20Video%20from%20cmd%20using%20python)

**Comment by Nimit-Khurana** [comment]
This works fine. but why does [ urllib.request.urlretrieve(url, name) ] this not work in the run.py file??

**Comment by ankitjain28may** [comment]
This is because, youtube video url isn't a downloadable link of a video so it cant download video using that link, we need to parse the youtube link to a downloadable link to download a video

**Comment by Nimit-Khurana** [comment]
This works fine. but why does [ urllib.request.urlretrieve(url, name) ] this not work in the run.py file??
